'''Don't need to use this file to generate bt matrices - I use it to get the dish positions, redundant baselines, etc. for the nominal (unperturbed) 
array'''
config:
    beamtransfers:      Yes
    kltransform:        Yes
    psfisher:           No

    output_directory:   ./bt_matrices_nominal

telescope:
    type:
        # Mechanism to specify a custom class
        class:  HIRAXSurvey
        module: hirax_transfer.core

    # For a single pointing use:
    #
    pointing_start: 0
    pointing_stop: 0
    npointings: 1

    hirax_spec:
        # Set band parameters:
        freq_lower: 600.
        freq_upper: 600.78125
        num_freq: 2
        # Other parameters (See drift.core.telescope)
        auto_correlations: No
        tsys_flat: 50.0
        redundancy_boost: 64.0
        dish_width: 6.0
        num_pol_sky: 1
        lmax: 200
        mmax: 200
        ndays: 1 # When noise weighting is needed, will assume an integration
                   # time of this many days.

        hirax_layout: # See hirax_transfer.layouts
            type: square_grid
            spacing: 6.0
            grid_size: 3

        hirax_beam: # See hirax_transfer.beams
            type: airy
            diameter: 6.

kltransform:

    - type: KLTransform
      name: kl_fg_0thresh
      inverse: Yes
      threshold: 0
      use_thermal: Yes
      use_foregrounds: No
      use_polarised: No
